### ISSUE TITLE
getting error while running "explain" function

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [awsm-research/PyExplainer#19]
Hello,
I am trying to use pyexplainer for input as text data of bug reports. I have performed text vectorizer. and after that while performing this step: 
<code> created_rules = py_explainer.explain(X_explain=X_explain,
                                     y_explain=y_explain,
                                     search_function='crossoverinterpolation',
                                     random_state=0,
                                     reuse_local_model=True)
</code>

I am getting this error:
<code> 
Traceback (most recent call last):
  File "sh_project.py", line 49, in <module>
    created_rules = py_explainer.explain(X_explain=X_explain,
  File "/mnt/c/Users/shrad/Documents/PyExplainer/pyexplainer/pyexplainer_pyexplainer.py", line 554, in explain
    synthetic_object = self.generate_instance_crossover_interpolation(
  File "/mnt/c/Users/shrad/Documents/PyExplainer/pyexplainer/pyexplainer_pyexplainer.py", line 848, in generate_instance_crossover_interpolation
    X_train_i = X_train_i.loc[:, self.indep]
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1149, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 827, in _getitem_tuple_same_dim       
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1191, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1327, in _get_listlike_indexer        
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict      
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/shraddha/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5842, in _raise_if_missing        
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['bookmarks option',\n       '[FIX]Not correctly retrieving post data when saving a page or frame generated from a form POST',\n       'Show URI in status bar onmouseover of Back/Forward menu items',\n       'Localization problems with Bookmarks Sorted By menu & History Sorted By menu',\n       'UI to allow external handlers for internal types',\n       'Mozilla should support X11 session management',\n       'POST result page should not appear in global history or history autocomplete results',\n       'Non-responding Windows UNC share hangs bookmark menu',\n       'want infinite Back', 'Use favicons on webpage shortcuts in Windows'],\n      dtype='object', name='Title')] are in the [columns]"
</code>

Can anyone please help, what does this error indicate?

**Comment by MichaelFu1998-create** [comment]
Hi, may I have details of both variables X_explain and y_explain?
Thanks!

**Comment by ShraddhaDevaiya** [comment]
yeah, X_explain and y_explain is like this:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/29624037/181518149-cb1d22ea-5426-48ae-8cba-0f26311db05b.png">

<img width="167" alt="image" src="https://user-images.githubusercontent.com/29624037/181518257-adee35a6-4f78-4173-85a7-a4272036c0c1.png">

**Comment by MichaelFu1998-create** [comment]
Hi @ShraddhaDevaiya,
How did you construct the PyExplainer object? 
Did you set the "indep" (feature columns names) and "dep" (label column name) variables?
Also, you may follow the "PART B" in this tutorial file https://github.com/awsm-research/PyExplainer/blob/master/TUTORIAL.ipynb
let me know if it helps

**Comment by MichaelFu1998-create** [comment]
Feel free to open another issue if still having issues running our package.
